version: 2.1
# Orbs - Reusable packages for use.
orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.6.0

# Jobs - Set of instructions / Functions.
jobs:
  build: # Job name.
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest --version
          name: Test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: nhkhai/container-assignment
          tag: latest
      - docker/push:
          image: nhkhai/container-assignment
          tag: latest

  deploy:
    docker:
      # - image: cimg/deploy:2024.03
      - image: cimg/base:current-22.04
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Render Deploy Hook
          command: |
            curl "$RENDER_DEPLOY_HOOK_URL"

# Workflow - Defines what sequence will the jobs run.
workflows:
  simple_workflow: # Workflow name.
    jobs:
      - build
      - publish:
          requires:
            - build
      - deploy:
          requires:
            - publish
